
# Dependencies
markdown:         kramdown

# Permalinks
#permalink:        pretty

# Setup
title:            'Calculus Book'
tagline:          'from http://cnx.org/contents/9a1df55a-b167-4736-b5ad-15d996704270@5.1 (CC-BY-NC-SA)'
url:              https://github.com/philschatz/calculus-book
origin:           http://cnx.org/contents/9a1df55a-b167-4736-b5ad-15d996704270@5.1

author:
  name:           'Openstax'
  url:            https://github.com/openstax

paginate:         5

# Custom vars
version:          5.1

bookviewer:       https://philschatz.com/book-viewer

